site_name: RAG System Developer Documentation
site_description: Developer documentation for the hybrid RAG retrieval system
site_author: Development Team
repo_url: https://github.com/yourusername/hackathon
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/overview.md
      - Data Flow: architecture/data-flow.md
      - Database Schema: architecture/database.md
  - Components:
      - Ingestion Pipeline: components/ingestion.md
      - Search & Retrieval: components/search.md
      - Context Expansion: components/context-expansion.md
  - AI/ML Concepts:
      - RAG Explained: concepts/rag.md
  - Development:
      - Getting Started: development/setup.md
      - Running the System: development/usage.md
      - Testing: development/testing.md
      - Contributing: development/contributing.md
